require('./angular.min.js');
require('./slider.js');
require('./bootstrap-colorpicker-module.min.js');
//require('./bootstrap.min.js');
require('./main.js');
require('./game.js');
require('./sketchpad.js');
require('./sandbox.js');
require('./clock.js');
